services:
  db:
    container_name: my-mysql-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"  # MySQL exposed to host as port 3307
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    container_name: my-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "8082:80"  # phpMyAdmin exposed to host:8082
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8181:8080"  # Adminer exposed on host:8181

volumes:
  mysqldata:
